
import { from, Observable } from 'rxjs';
import { Order } from 'src/models/order.model';
import { Product } from 'src/models/product.model';

export class ProductData {
private products: Product[] = [
    new Product(1, "Kayak", "Watersports", 275, "Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(2, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(3, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(4, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(5, "Thinking Cap", "Chess", 16,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(6, "Thought Box", "Chess", 20,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(7, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(8, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(9, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(10, "Thinking Cap", "Chess", 16,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(11, "Thought Box", "Chess", 20,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(12, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(13, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(14, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(15, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(16, "Thinking Cap", "Chess", 16,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(17, "Thought Box", "Chess", 20,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(18, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(19, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(20, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(21, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(22, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(23, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(24, "Thinking Cap", "Chess", 16,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(25, "Thought Box", "Chess", 20,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(26, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(27, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(28, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(29, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(30, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(31, "Thinking Cap", "Chess", 16,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(31, "Thought Box", "Chess", 20,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(33, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(34, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(35, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(36, "Thinking Cap", "Chess", 16,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(37, "Thought Box", "Chess", 20,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(38, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(39, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(40, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(42, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(43, "Thinking Cap", "Chess", 16,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(44, "Thought Box", "Chess", 20,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(45, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(46, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(47, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(48, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(49, "Soccer Ball", "Soccer", 19.50,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(50, "Corner Flags", "Soccer", 34.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(51, "Thinking Cap", "Chess", 16,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(52, "Thought Box", "Chess", 20,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
    new Product(53, "Lifejacket", "Watersports", 48.95,"Nesciunt aperiam sint ut. Incidunt sit sed et. Ea sed voluptate rem quod iusto hic veniam repellat velit. Nihil est ipsam ipsum cum accusantium omnis laudantium voluptates quo. Ut itaque nulla est iste quibusdam placeat repellat est. Explicabo ullam fuga autem quod.", true, false),
];
    
    getData(): Observable<Product[]> {
     return from([this.products]);
    }
    saveOrder(order: Order): Observable<Order> {
        console.log(JSON.stringify(order));
        return from([order]);
    }
     

}